### ISSUE TITLE
iOS Devices Can't Connect To VPN/Pistrong

### ISSUE THREAD

**Issue by ethanic17** [gitbls/pistrong#15]
So for about two years (close to one and a half?) now, I've been using pistrong to access my files & Pi at home, but now I'm having a bit of trouble with getting it to work. I recently got an iPad and I tried adding it as a device & installed the certs but it doesn't work. I got all the certs to install properly and I actually _can_ connect to it (like the little VPN icon shows up), but I can't access anything (terminal, webpages, files, etc.) as it just says it can't connect to the server/server issue. And my iPhone also stopped allowing me to connect (or same with the iPad, as in the VPN icon pops up and says I'm connected, but I can't do anything). Interestingly, my Windows device & cert remained intact so I suspect it's something specific pertaining to the iOS connection/cert.

I opened up a similar issue about two years ago (Closed Issue #10), and I tried retracing all the steps I took, but perhaps something changed with iOS certifications through an iOS update that caused this issue (like the switch to iPadOS instead of iOS)? Or maybe I messed up somewhere along the process? 

Here are the devices listed (as you can see, the 2021 certs are from when I first setup Pistrong, and the 2023 cert is the newest one, ignore the ethan-iphone11 ):
![image](https://github.com/gitbls/pistrong/assets/41976386/b81d37bd-6802-41d8-aee2-577c364a1035)

And here's the command I used to setup the new device (iPad): 
![image](https://github.com/gitbls/pistrong/assets/41976386/9add6c8d-6921-4e01-ae2c-c1a3a68f289f)

And this is off-topic, but I remember when I first worked with you on this, you mentioned a paid SSH application on iOS/iPadOS that was pretty good and I never got the chance to check it out. I can't seem to find it after searching through #10 and the emails we exchanged, so I was hoping if you still remember/use it, could you let me know what it is? Thanks!

**Comment by gitbls** [comment]
pscollect is a file on this github. Please download/run it (you'll probably need to change the file protection to 755 first), and get me the output.
