### ISSUE TITLE
Site to Site VPN on same subnet

### ISSUE THREAD

**Issue by kriszabala** [gitbls/pistrong#4]
Running the `makeTunnel` script says the following: "NOTE: LocalNet1 and LocalNet2 cannot be the same subnet (e.g., 192.168.1.0/24 on both networks)"

I'm trying to implement a site to site tunnel with both ends on the same subnet 192.168.1.0/24. Would it be possible if the routers on both ends used non colliding ip ranges? 
e.g. LocalNet1 Router dchp range 192.168.1.2-128 
       LocalNet2 Router dchp range 192.168.1.129-255

**Comment by gitbls** [comment]
I have never tried this. The key issue in the case of both ends on the same subnet are the iptables rules in the nat POSTROUTING table. These are used to route packets back to the remote end of the VPN. It _might_ be possible to change the rules created by makeTunnel to make this work, but I'm a bit skeptical.

The best solution, of course, is to re-IP one of the networks so you can use standard netmasks and everything will just work. 

If that's not possible, my suggestion would be to use one of the IP calculators on the net to see if you can convince yourself that this is viable.

If you go down this path, I'll be happy to consult with you on it here.

**Comment by kriszabala** [comment]
Thanks, due to your skepticism and suggestion, I will try re-ip one of the networks.
